all: 	
	g++ -w -lpthread -DTERMINAL Pos.cpp ChessBoard.cpp Move.cpp Game.cpp tests/main.cpp  -o chess

pg:
	g++ -w -lpthread -DTERMINAL -g Pos.cpp ChessBoard.cpp Move.cpp Game.cpp tests/main.cpp  -o chess

clean:
	rm -rf *o chess
