all: 	
	g++ -w -lpthread -DTERMINAL Pos.cpp ChessBoard.cpp Move.cpp Game.cpp main.cpp  -o chess

pg:
	g++ -w -lpthread -DTERMINAL -pg Pos.cpp ChessBoard.cpp Move.cpp Game.cpp main.cpp  -o chess

clean:
	rm -rf *o chess
